<?php
// Regenerates src/parsers/php_builtin_functions.txt, the built-in PHP functions whose calls the
// PHP parser does not record. Sources: the running PHP (with its loaded extensions) and, when a
// path to phpstan.phar is given, PHPStan's function map, which covers extensions not installed
// locally (gd, bcmath, …).
//
//   php scripts/php-builtin-functions.php [path/to/phpstan.phar] > src/parsers/php_builtin_functions.txt

$names = get_defined_functions()['internal'];
$sources = 'PHP ' . PHP_VERSION . ' (' . implode(' ', get_loaded_extensions()) . ')';

if (isset($argv[1])) {
    $map = require 'phar://' . realpath($argv[1]) . '/resources/functionMap.php';
    $names = array_merge($names, array_keys($map));
    $sources .= ', PHPStan functionMap';
}

$names = array_map('strtolower', $names);
// Map keys also hold methods (`Foo::bar`) and overload variants (`foo'1`).
$names = array_filter($names, static fn(string $name): bool => 1 === preg_match('/^[a-z_][a-z0-9_]*$/', $name));
$names = array_unique($names);
sort($names);

echo "# Built-in PHP functions. Generated by scripts/php-builtin-functions.php from {$sources}.\n";
echo implode("\n", $names), "\n";
